version: '3.9'

volumes:
  dados:

networks:
  web:
    name: rede-web
    driver: bridge
  banco:
    name: rede-banco
    driver: bridge
  fila:
    name: rede-fila
    driver: bridge

services:
  db:
    image: postgres:9.6
    container_name: db-postgres-9.6
    # entrypoint: /docker-entrypoint-initdb.d/init.sql
    volumes:
      # Volumes dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - banco

  frontend:
    image: nginx:latest
    container_name: frontend-nginx
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Proxy configuração
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - web
    depends_on:
      - app

  app:
    image: python:3.6
    container_name: app-python
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080
    networks:
      - web
      - banco
      - fila
    depends_on:
      - db
      - queue

  queue:
    image: redis:latest
    container_name: queue-redis
    networks:
      - fila
  worker:
    image: python:3.6
    container_name: worker-python
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - fila
    depends_on:
      - queue